Update fastify-autoload.d.ts
fastify/fastify-autoload pull request #138
Opened 2021-02-23 17:56 UTC by Paol-imi

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-02-23 19:35 UTC, mcollina requested changes
could you add a test for those properties? Thanks!

2021-02-23 20:21 UTC, Paol-imi commented
Of course, I added the pull request before writing because I had some issues with the current tests on my local machine.

2021-02-24 05:39 UTC, climba03003 approved these changes

2021-02-24 08:48 UTC, mcollina approved these changes
lgtm

2021-02-24 08:48 UTC, merged