feat: Added forceESM option.
fastify/fastify-autoload pull request #144
Opened 2021-03-09 15:17 UTC by ShogunPanda

This PR adds the `forceESM` option, which always uses `await import` to load modules despite of the detected package type.

I run into this when running code via `ts-node` in a folder where `package.json` had `type='module'`.

I also tried to add a test for this, but I was not able to reproduce the problem in this repo, since `type!='module'`.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-03-10 11:52 UTC, mcollina requested changes
Could you add a unit test for this new functionality? It's not just a definition change.

2021-03-10 15:12 UTC, ShogunPanda commented
I already tried above but I was not able to reproduce the problem within the repo.

I've tried again with several strategies. Unfortunately I haven't succeeded.
What shall we do?

2021-03-10 21:08 UTC, ShogunPanda commented
Done!

2021-03-11 05:15 UTC, climba03003 commented
Can you fix the failing CI?

2021-03-11 09:11 UTC, ShogunPanda commented
Sure, it's fixed now!

2021-03-11 13:11 UTC, RafaelGSS commented
What problem this solves? Reading the description seems to me that `fastify-autoload` doesn't support esm yet.

> I run into this when running code via ts-node in a folder where package.json had type='module'.

 That's it?

2021-03-11 13:15 UTC, ShogunPanda commented
No, it's actually a (not sure how much) edge case with TypeScript.

If you use `ts-node` in a folder whose applicable `package.json` has `type=module`, fastify-autoload will fail.

This is because of the following stesp: 

1. `https://github.com/fastify/fastify-autoload/blob/master/index.js#L98` return `typescript`.
2. `https://github.com/fastify/fastify-autoload/blob/master/index.js#L216` will therefore attempt to load using `require`.
3. Since `type=module`, `.js` (or `.ts`) files are interpreted by default from Node as ESM and thus `require` shall not be used and will fail.

My PR fixes step 2 by adding a `forceESM` that bypasses detection in step 1.

2021-03-11 13:25 UTC, RafaelGSS commented
Ok, thanks!

2021-03-11 13:25 UTC, RafaelGSS approved these changes
LGTM.

2021-03-11 14:36 UTC, mcollina approved these changes
lgtm

2021-03-11 14:54 UTC, merged