271: trying to use tsnode when using typescript files
fastify/fastify-autoload pull request #272
Opened 2022-10-07 07:38 UTC by lasmil

- when dealing with typescript files, we need to make sure the ts-node is being used to autoload components
- closes: https://github.com/fastify/fastify-autoload/issues/271

2022-10-07 07:43 UTC, climba03003 requested changes
I don't see any different from https://github.com/fastify/fastify-autoload/pull/264

2022-10-07 07:50 UTC, simoneb commented on index.js
> +      if (!typescriptSupport) {
nesting two ifs this way is the same as what it was before, why not just keep it as it was?

2022-10-07 07:57 UTC, lasmil commented
> 
There is a difference between the 2 PRs. In this PR I am using:
const type = getScriptType(file, options.packageType)
the type to know if it's 'typescript' or not.

In the other (reverted) PR we are trying to require ts-node even when the type is not 'typescript'.

2022-10-07 07:57 UTC, simoneb commented
approach looks reasonable, let's add tests to confirm it works!

2022-10-07 07:58 UTC, climba03003 commented
> There is a difference between the 2 PRs. In this PR I am using: `const type = getScriptType(file, options.packageType) ` the type to know if it's 'typescript' or not.
> 
> In the other (reverted) PR we are trying to require ts-node even when the type is not 'typescript'.

Still, it didn't convince me why we need to explicitly register `ts-node` for the user.
In the issue, I don't see `ts-node` as devDependency. How can explicitly register `ts-node` can solve the problem of someone that do not install it?

The solution should be detect if the current script run under `babel-node` and allow it as `typescript` runtime.

2022-10-07 08:01 UTC, lasmil commented
> 

When I tried with the mentioned project I did indeed needed to install ts-node as a dev dependency. Let me try your solution.

2022-10-07 12:28 UTC, lasmil commented
> > 
> 
> When I tried with the mentioned project I did indeed needed to install ts-node as a dev dependency. Let me try your solution.



> > There is a difference between the 2 PRs. In this PR I am using: `const type = getScriptType(file, options.packageType) ` the type to know if it's 'typescript' or not.
> > In the other (reverted) PR we are trying to require ts-node even when the type is not 'typescript'.
> 
> Still, it didn't convince me why we need to explicitly register `ts-node` for the user. In the issue, I don't see `ts-node` as devDependency. How can explicitly register `ts-node` can solve the problem of someone that do not install it?
> 
> The solution should be detect if the current script run under `babel-node` and allow it as `typescript` runtime.

I have pushed a commit to this PR. I tried to find a better way to detect if the script is running under babel-node but unfortunately I was unable to find it.

2022-10-07 16:42 UTC, simoneb approved these changes
a few comments but overall LGTM

2022-10-07 16:42 UTC, simoneb commented on test/typescript-jest/babel-node/index.test.ts
> +    expect(JSON.parse(response.payload)).toEqual({ hello: 'world' })
```suggestion
    expect(response.json()).toEqual({ hello: 'world' })
```

2022-10-07 16:42 UTC, simoneb commented on test/typescript-jest/babel-node/index.test.ts
> +  })
nit: let's use newer async/await syntax

2022-10-07 16:42 UTC, simoneb commented on test/commonjs/babel-node/routes/foo/index.ts
> +};
formatting: let's use quotes consistently, either single or double

2022-10-07 16:42 UTC, simoneb commented on test/typescript-jest/babel-node/index.test.ts
> +    })
if you're GETting root you don't need this variant of inject, simple inject('/')

2022-10-09 16:59 UTC, mcollina approved these changes
lgtm

2022-10-09 17:00 UTC, mcollina commented
@climba03003 PTAL

2022-10-09 17:04 UTC, climba03003 approved these changes

2022-10-09 17:05 UTC, merged