feat: Add Bun and Deno to typescript support check
fastify/fastify-autoload pull request #408
Opened 2024-08-24 15:38 UTC by Codex-

This change allows the Bun and Deno runtimes to use this loader with Fastify base without erroring as seen in #317.

### Tests

#### Node

No regressions, everything passing.

#### Bun

- `bun run typescript` ✅
- `bun run typescript:jest` ✅
- `bun run typescript:vitest` ✅
- `bun run unit` ✅
  - `unit.js` updated to consume an arg for the runtime
- The bun equivalent of the loader tests that execute `test/typescript/basic.ts` cannot be run as a particular function Tap uses has not yet been implemented in Bun
  - `NotImplementedError: node:v8 Serializer is not yet implemented in Bun.`

#### Deno

- `deno task typescript` ✅
- Deno implements `ServerResponse` as a class, while node a function, which causes this error in Fastify.
  - `Class constructor ServerResponse cannot be invoked without 'new'`
  - This causes the following to fail
    - `deno task typescript:jest` ❌
    - `deno task typescript:vitest` ❌
    - `deno task unit` ❌

While it has already been communicated that Fastify is not actively supporting either Bun or Deno runtimes, despite the results, it would be great to see this check updated to allow their usage at a "ymmv" degree.

Fixes #317 

#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [x] ~documentation is changed or added~
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-08-24 15:40 UTC, mcollina requested changes
Currently we do not support Bun or Deno on Fastify.
Frankly, we have not time, and I would not accept a PR without tests either.

https://github.com/fastify/fastify/blob/main/docs/Reference/LTS.md#long-term-support

2024-08-24 15:51 UTC, Codex- commented
> Currently we do not support Bun or Deno on Fastify. 

While I understand that is the official stance, as noted in your link, with all of the other supported tooling already included would it really do any harm to simply allow this check to pass for these runtimes? 

>and I would not accept a PR without tests either.

You beat me to it, I amended my commit with the bun tests I intended to push originally :)

Fastify is simply incompatible with Deno currently, I'm happy to include another test run file to run against deno but it will fail and not add value

2024-08-24 16:05 UTC, mcollina commented on scripts/unit.js
> +const child = exec(argv[2] + ' run unit:with-modules')
Can you please add `npm` as a default?

You'd need to add `bun` to CI as well.

2024-08-24 16:16 UTC, Codex- commented on scripts/unit.js
> +const child = exec(argv[2] + ' run unit:with-modules')
Sure can

I was going to ask actually, so the CI currently uses that [shared workflow](https://github.com/fastify/workflows/blob/v5.0.0/.github/workflows/plugins-ci.yml) from the workflows repo, so to not muddy concerns in that workflow, would you be happy with an additional job added to the `ci.yml` that performs the tests for bun?

```yml
jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v5.0.0
    with:
      license-check: true
      lint: true
  bun:
    uses: ...
```

2024-08-25 03:35 UTC, Codex- commented on scripts/unit.js
> +const child = exec(argv[2] + ' run unit:with-modules')
Went with adding a job to the existing workflow for now, the erroneously published version `aplha` takes precedence over `alpha` in string ordering so until it reaches beta the workflow needs to specifically install the version required for tests to satisfy the `semver` usage (since `semver` doesn't recognise `aplha` as a valid version)

2024-08-25 06:58 UTC, Eomm commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v4
```suggestion
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
```

2024-08-25 06:58 UTC, Eomm commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    continue-on-error: true
```

2024-08-26 03:03 UTC, mcollina approved these changes
lgtm

2024-08-26 07:33 UTC, gurgunday commented on .github/workflows/ci.yml
> +          bun i -D --ignore-scripts fastify@5.0.0-alpha.3
This is not ideal

The typod version seems to be unpublished now — can't find it at https://www.npmjs.com/package/fastify?activeTab=versions

Can you try removing the line?

```suggestion
```

2024-08-26 08:12 UTC, Codex- commented on .github/workflows/ci.yml
> +          bun i -D --ignore-scripts fastify@5.0.0-alpha.3
You can't unpublish a package from npm:

![image](https://github.com/user-attachments/assets/a4d14449-ca46-4742-88c9-22c910f4de93)

2024-08-26 08:27 UTC, gurgunday approved these changes

2024-09-02 21:20 UTC, Codex- commented on .github/workflows/ci.yml
> +          bun i -D --ignore-scripts fastify@5.0.0-alpha.3
Because of the typo in the version name bun takes `p` as being of a higher version than `l` when parsing `aplha`

`aplha.1` does not pass the tests

Can be removed once beta has begun

2024-09-10 14:12 UTC, MrEAlderson commented
Please merge, this is the only problem I have faced regarding bun support in fastify.
For anyone else stumbling on this: Adding `FASTIFY_AUTOLOAD_TYPESCRIPT=true` to your .env is a temporary fix

2024-09-10 16:07 UTC, gurgunday commented on .github/workflows/ci.yml
> +          bun i -D --ignore-scripts fastify@5.0.0-alpha.3
I can confirm this is the case

2025-10-24 14:54 UTC, ilteoood commented
@gurgunday any news about this?

2025-10-24 21:36 UTC, gurgunday commented
@ilteoood honestly I totally forgot about this one, you (or the original author) can take it over

2025-10-24 22:07 UTC, Uzlopak commented
The repo is archived. So no way to keep this PR.

2025-10-24 22:07 UTC, closed without merging

2025-10-25 09:51 UTC, Uzlopak commented
Superseeded by #480